# Generated by Django 4.2.4 on 2023-08-18 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_reserva_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data',
        ),
    ]
