# Generated by Django 4.2.4 on 2023-08-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('nome_pet', models.CharField(max_length=50, verbose_name='nome do pet')),
                ('data', models.DateField(help_text='dd/mm/aaaa', verbose_name='data')),
                ('turno', models.CharField(choices=[('manhã', 'manhã'), ('tarde', 'tarde')], max_length=10, verbose_name='Turno')),
                ('tamanho', models.IntegerField(choices=[(0, 'piqueno'), (1, 'médio'), (2, 'grande')], verbose_name='tamanho')),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
    ]
